### ISSUE TITLE
New Sageone api version filter?

### ISSUE THREAD

**Issue by mikeyduece** [Jetbuilt/omniauth-sageone#5]
I've started an integration with Sageone. I'm using your gem to authenticate and creating the client on my own to interact with the API. Previously, I was able to authenticate without issue as I mistakenly created a demo app on their older version. When clicking on the warning to update my code for the newer api, they instruct to add a filter query param to the token url. 
`https://www.sageone.com/oauth2/auth/central?filter=apiv3.1` 
I am now receiving invalid client errors when attempting to authorize with this gem. I get to what I'm assuming is the correct authorize url, it shows the correct application name and image. But when I click accept, in my server, it errors with invalid client. I've triple checked my client id and secret and they match. Not really sure where/how the error is occurring.

**Update:** I am able to pass the new query param into the authorize_params. But it still comes back with invalid client. The authorize url points to the correct application, the name and picture are correct.

**Comment by mheft-showoff** [comment]
Update to above. Forked the repo and tested with new urls and it works. Will submit pull request after further testing :D

**Comment by jaredmoody** [comment]
I knew things were changing with the v3 api, but had not updated this yet. I look forward to the PR!

**Comment by jaredmoody** [comment]
Closed by #9
